### ISSUE TITLE
Bot keeps responding that it is at capacity

### ISSUE THREAD

**Issue by fredjt** [MrlolDev/chatgpt-discord-bot#5]
Bot rarely gives an actual result and instead keeps telling me to wait. Is it possible to queue requests until they can be processed?

**Comment by ShreshthTiwari** [comment]
Nobody can do anything about it because the ChatGPT API is overloaded due to heavy traffic and comparably less powerful system to handle all those requests.

**Comment by MrlolDev** [comment]
This issue was mainly because the huge amount of usage of the bot but the few amount of accounts we had. As a result we decides to move to gpt-3 official API which is more reliable, once the official ChatGPT API is launched we will add it.

**Comment by MrlolDev** [comment]
Bot rechanged to official chatgpt endpoint no more errors
